NOMES_MASCULINOS = [
    "Ademir", "Adriano", "Afonsino", "Afrânio", "Albano", "Alberto", "Aldo", "Alef", "Alex", "Alexandre",
    "Alfredo", "Allan", "Almir", "Aloísio", "Altair", "Alvaro", "Amadeu", "Amauri", "Américo", "Anderson",
    "André", "Angelo", "Anselmo", "Antenor", "Anthony", "Antonio", "Apóstolo", "Aquiles", "Ariel", "Ariosto",
    "Armando", "Arnaldo", "Aroldo", "Arthur", "Arão", "Asdrubal", "Assis", "Atila", "Augusto", "Aurélio",
    "Avelino", "Baltazar", "Barnabé", "Bartholomeu", "Belmiro", "Benedito", "Benito", "Benjamin", "Bento",
    "Bernardo", "Betinho", "Beto", "Breno", "Brian", "Bruce", "Bruno", "Caio", "Caique", "Calebe", "Calisto",
    "Candido", "Capanema", "Carlos", "Carmine", "Cassiano", "Cauã", "Cesario", "Charles", "Christiano", "Cicero",
    "Cirilo", "Ciro", "Claus", "Cleber", "Clementino", "Clodomir", "Clodoaldo", "Cláudio", "Conrado", "Constantino",
    "Cristiano", "Cristovão", "César", "Dagoberto", "Dalmo", "Dalmir", "Dalton", "Damian", "Daniel", "Danilo",
    "Dante", "Davi", "David", "Davino", "Denis", "Diego", "Diogo", "Dirceu", "Diógenes", "Djalma", "Domingos",
    "Dominique", "Donizete", "Douglas", "Décio", "Edgar", "Edilson", "Edimar", "Edmundo", "Edson", "Edu", "Eduardo",
    "Edvaldo", "Efraim", "Elcio", "Eldorado", "Elias", "Eliezer", "Eliomar", "Eliseu", "Emanuel", "Emerson",
    "Emiliano", "Emilio", "Enoque", "Enrico", "Erasmo", "Eric", "Erik", "Ernesto", "Ernani", "Ernesto", "Esdras",
    "Estevan", "Euclides", "Euler", "Eurico", "Eustáquio", "Evaristo", "Everson", "Everton", "Ezequiel",
    "Ezio", "Fabiano", "Fabio", "Fabrício", "Fernando", "Filipe", "Flavio", "Fernandes", "Florisvaldo",
    "Francisco", "Fábio", "Feliciano", "Felipe", "Fernando", "Firmino", "Flávio", "Floriano", "Flávio", "Francesco",
    "Francisco", "Franklin", "Frederico", "Gabriel", "Galdino", "Gastão", "Geovane", "Germano", "Geraldo",
    "Gerônimo", "Gerson", "Gil", "Gilberto", "Gildo", "Giovani", "Giovanni", "Gleison", "Gonçalo", "Gustavo",
    "Hans", "Haroldo", "Hector", "Helder", "Heitor", "Heleno", "Helder", "Heloísa", "Helvécio", "Heraldo",
    "Herbert", "Hercules", "Hermano", "Hermenegildo", "Hermínio", "Hernandes", "Higor", "Hildebrando",
    "Hiran", "Hugo", "Humberto", "Hércules", "Iago", "Ibrahim", "Icaro", "Igor", "Inácio", "Irineu", "Isaac",
    "Ismael", "Isaías", "Israel", "Ícaro", "Índio", "Ivaldo", "Ivan", "Ivo", "Jackson", "Jacó", "Jaime", "Jair",
    "Jamerson", "Jan", "Janderson", "Jansen", "Jarbas", "Javier", "Jayme", "Jefferson", "Jeronimo", "Jesué",
    "Jetro", "Joaquim", "Joel", "Jonas", "Jonathan", "Jorge", "Josenildo", "Josias", "Josué", "Jovino",
    "Juarez", "Julião", "Julinho", "Julio", "Junior", "Juninho", "Jurandir", "Jânio", "Júlio", "Kaique",
    "Kauã", "Kauê", "Kelvin", "Kennedy", "Kleber", "Kléber", "Laércio", "Lamar", "Laurindo", "Lazaro",
    "Lauro", "Laércio", "Laurindo", "Leandro", "Leonardo", "Leônidas", "Leopoldo", "Leto", "Levi", "Lewis",
    "Licio", "Lindolfo", "Lino", "Lincoln", "Lisandro", "Lisandro", "Lívio", "Logan", "Lourenço", "Lucas",
    "Luciano", "Lucien", "Luiz", "Luis", "Luzia", "Lázaro", "Lúcio", "Macedo", "Márcio", "Mário", "Maikon",
    "Manoel", "Manuel", "Marcel", "Marcelo", "Márcio", "Marco", "Marcos", "Marcus", "Mariano", "Mario",
    "Marlon", "Márcio", "Martin", "Matheus", "Mauricio", "Mauro", "Max", "Melquisedeque", "Messias", "Micael",
    "Michael", "Michel", "Miguel", "Moacir", "Moises", "Murilo", "Murilo", "Nathan", "Natal", "Natanael",
    "Natan", "Nelson", "Nereu", "Newton", "Nicolau", "Nildo", "Nivaldo", "Noé", "Norberto", "Norival",
    "Odair", "Odilon", "Olavo", "Oliver", "Olivier", "Omar", "Ondino", "Orlando", "Orley", "Oséias",
    "Osvaldo", "Oswaldo", "Otávio", "Otto", "Pablo", "Patrick", "Patrício", "Paulo", "Pedro", "Percival",
    "Péricles", "Pietro", "Pablo", "Pascoal", "Paulino", "Paulo", "Pedro", "Plinio", "Quintino", "Quirino",
    "Rafael", "Raimundo", "Raimundo", "Ralf", "Ramon", "Ramón", "Raphael", "Raul", "Raymundo", "Reginaldo",
    "Ricardo", "Roberto", "Rodolfo", "Rodrigo", "Roger", "Rogerio", "Roque", "Rudinei", "Rudolf", "Rui",
    "Ruy", "Samuel", "Sandro", "Santiago", "Sávio", "Sebastião", "Sergio", "Sérgio", "Sílvio", "Silvio",
    "Simão", "Sócrates", "Stanislau", "Stanley", "Sylvio", "Tadeu", "Tales", "Tarcísio", "Tasso", "Thales",
    "Theo", "Thiago", "Thomas", "Tobias", "Tomás", "Tony", "Ulisses", "Ulysses", "Umberto", "Urias",
    "Valdemar", "Valdir", "Valentim", "Valter", "Vanderlei", "Vando", "Vicente", "Victor", "Vilmar",
    "Vinicius", "Virgílio", "Vital", "Vitor", "Vítor", "Vladimir", "Wagner", "Waldo", "Wallace",
    "Washington", "Walter", "Wanderley", "Wanderson", "Wellington", "Wesley", "Wilker", "William",
    "Wilson", "Wilton", "Xavier", "Yago", "Yan", "Ygor", "Yuri", "Yves", "Zaqueu", "Zé", "Zeno",
    "Zico", "Zildo", "Zito", "Álvaro", "Ângelo", "Édson", "Ícaro", "Ígor", "Óliver", "Óscar", "Úrsulo",
    "Óscar", "Ósmar", "Ênio", "Ítalo", "Ítalo"
]

NOMES_FEMININOS = [
    "Adriana", "Adriane", "Alessandra", "Alice", "Aline", "Aline", "Amanda", "Amélia", "Anita", "Angela", "Andressa", "Anita", "Ariane", "Beatriz", "Bianca", "Bianca", "Bruna", "Camila", "Carla", "Carla", "Carmem", "Caroline",
    "Cassia", "Catarina", "Cécilia", "Célia", "Cida", "Cíntia", "Clara", "Claudete", "Cláudia", "Cléo", "Cristiane", "Cristal", "Cristina", "Dalila", "Daniela", "Daniele", "Dayane", "Débora", "Déborah", "Diana", "Dora", "Duda",
    "Édina", "Élida", "Érica", "Érika", "Elaine", "Elis", "Elisa", "Elisângela", "Elizete", "Emmanuelle", "Ester", "Esther", "Eunice", "Evelyn", "Evangelina", "Fabiana", "Fabíola", "Fabíola", "Fátima", "Fabiola", "Fernanda",
    "Fernanda", "Flávia", "Francisca", "Gabriela", "Geovana", "Giovanna", "Gisele", "Glória", "Graziela", "Graciele", "Helena", "Hortência", "Iara", "Iris", "Isabela", "Isabela", "Isadora", "Isabella", "Janaina", "Jaqueline",
    "Joana", "Júlia", "Juliana", "Juliana", "Juliane", "Juliane", "Kátia", "Kelly", "Laura", "Laís", "Larissa", "Laura", "Leila", "Letícia", "Leticia", "Lilian", "Lina", "Lídia", "Liz", "Lorena", "Luciana", "Luciele", "Lucilene",
    "Lucinda", "Ludmila", "Luzia", "Maga", "Malu", "Marcela", "Marcela", "Mariana", "Marilene", "Marisa", "Marlene", "Marta", "Michele", "Michele", "Mirian", "Monica", "Mônica", "Nádia", "Natália", "Nathalia", "Nicole", "Noemi",
    "Olívia", "Pâmela", "Patrícia", "Paula", "Penélope", "Poliana", "Priscila", "Rafaela", "Rafaela", "Raquel", "Regina", "Renata", "Rebeca", "Rita", "Roberta", "Rosana", "Rosana", "Rosângela", "Roselaine", "Roseli", "Rosimar",
    "Rosa", "Sabrina", "Sâmela", "Sandra", "Sheila", "Simone", "Silvana", "Sol", "Sol", "Solange", "Sofia", "Sônia", "Soraya", "Suellen", "Susana", "Talita", "Tânia", "Tânia", "Tatiana", "Tatiana", "Tatiane", "Tatiane", "Teresa",
    "Teresa", "Thaís", "Teresa", "Thaís", "Teresa", "Thaís", "Valéria", "Vanessa", "Vanessa", "Vanessa", "Vânia", "Vera", "Vera", "Vivian", "Viviane", "Viviane", "Wilma", "Yasmin"
]

SOBRENOMES = [
    "Abreu", "Aguiar", "Albuquerque", "Almeida", "Alves", "Amorim", "Andrade", "Antunes", "Araujo", "Araújo",
    "Arantes", "Arruda", "Assis", "Avelar", "Azambuja", "Barbosa", "Barreto", "Barros", "Bastos", "Batista",
    "Bezerra", "Bicalho", "Borges", "Brandão", "Braga", "Brito", "Britto", "Bueno", "Cabral", "Caetano",
    "Camara", "Câmara", "Campos", "Carneiro", "Caruso", "Carvalho", "Carraro", "Castro", "Cavalcante",
    "Cerqueira", "Chaves", "Coelho", "Cordeiro", "Cortez", "Costa", "Coutinho", "Couto", "Cruz", "Cunha",
    "Damasio", "Damasceno", "Dantas", "De Paula", "Delgado", "Dias", "Domingues", "Dominguez", "Drummond",
    "Duarte", "Escobar", "Estevam", "Farias", "Feldman", "Fernandes", "Ferrari", "Ferreira", "Fiorentini",
    "Fogaça", "Fontes", "Fonseca", "Fonseca", "Franco", "Freitas", "Furtado", "Fávero", "Galvão", "Garcia",
    "Goes", "Gois", "Gomes", "Goncalves", "Gonçalves", "Granja", "Guerra", "Guimarães", "Goulart", "Helena",
    "Henriques", "Horta", "Junqueira", "Lacerda", "Laurindo", "Leme", "Lima", "Lobo", "Lopes", "Luz", "Macedo",
    "Magalhães", "Marinho", "Marques", "Martins", "Matos", "Medeiros", "Melo", "Mendonça", "Menezes", "Mesquita",
    "Miguel", "Miranda", "Monteiro", "Montenegro", "Morais", "Moreira", "Moraes", "Morales", "Moura", "Muniz",
    "Nascimento", "Neves", "Nobre", "Noronha", "Nunes", "Oliveira", "Orozco", "Ortega", "Pacheco", "Paiva",
    "Penna", "Peixoto", "Pereira", "Pessoa", "Pimenta", "Pimentel", "Pina", "Pinto", "Pires", "Pitta", "Ponce",
    "Pontes", "Prado", "Queiroz", "Queiros", "Quintana", "Quintanilla", "Quintino", "Rabelo", "Ramirez", "Rangel",
    "Ramos", "Reis", "Ribeiro", "Rios", "Rocha", "Rodrigues", "Rosa", "Rosales", "Sales", "Salgado", "Salinas",
    "Sampaio", "Sanchez", "Sandoval", "Santana", "Santos", "Serra", "Serrano", "Silva", "Simões", "Siqueira",
    "Soares", "Sosa", "Souza", "Sá", "Sáenz", "Sánchez", "Sávio", "Tavares", "Taveira", "Teixeira", "Teles",
    "Tedesco", "Toledo", "Toscano", "Trindade", "Valença", "Valente", "Valerio", "Vargas", "Vasconcelos",
    "Vaz", "Velasques", "Velasquez", "Veras", "Vidal", "Vieira", "Vieites", "Vilela", "Vilhena", "Villar",
    "Vital", "Xavier", "Ximenes", "Zanetti", "Zapata"
]
